apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{interceptName}}'
  namespace: '{{interceptNamespace}}'
  labels:
    app: interceptor
    'system.codezero.io/session': '{{signatureHash}}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interceptor
      'system.codezero.io/session': '{{signatureHash}}'
  template:
    metadata:
      labels:
        app: interceptor
        'system.codezero.io/session': '{{signatureHash}}'
    spec:
      containers:
        - name: interceptor
          image:  nginx:1.17.10-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: intercept-nginx-config
      volumes:
      - name: nginx-conf-volume
        configMap:
          name: '{{interceptConfName}}'
