apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: sessions.system.codezero.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: system.codezero.io
  versions:
    - name: v1
      served: true
      storage: true
      # subresources:
      #   status: {}
      additionalPrinterColumns:
        - name: status
          type: string
          jsonPath: .status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: string
            spec:
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: sessions
    # singular name to be used as an alias on the CLI and for display
    singular: session
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Session
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - ss