/// <reference types="node" />
import { Resource, Result } from '@c6o/kubeclient-contracts';
import { baseProcessorMixinType } from './';
export declare const portForwardMixin: (base: baseProcessorMixinType) => {
    new (...a: any[]): {
        portForwardResult: Result;
        beginForward(containerPort: number, document: Resource): any;
        endForward(): any;
        cluster: import("..").Cluster;
        stageName?: any;
        sleep: (ms: any) => Promise<unknown>;
        commands: import("@c6o/kubeclient-contracts").commandFn[];
        additions: import("@c6o/kubeclient-contracts").commandFn[];
        waitListPromises: Promise<any>[];
        ended: boolean;
        currentCommand: import("@c6o/kubeclient-contracts").commandFn;
        lastCommand: import("@c6o/kubeclient-contracts").commandFn;
        lastResult: Result;
        waitList: (promise: Promise<any>) => number;
        ensureVersion(): Promise<void>;
        runWorker(): Promise<void>;
        do(cmd: import("@c6o/kubeclient-contracts").commandFn): any;
        end(): Promise<Result>;
        attempt(times: number, sleepTime: number, fn: import("@c6o/kubeclient-contracts").attemptCallback): any;
        copy(resource: Resource, src: string, dst: string): any;
        owners: Resource[];
        addOwner(object: Resource): any;
        clearOwners(): any;
        mergeDocument: Partial<Resource>;
        mergeWith(resource: Partial<Resource>): any;
        clearMergeWith(): any;
        list(object: Resource): any;
        read(object: Resource): any;
        create(object: Resource): any;
        patch(object: Resource, patch: import("@c6o/kubeclient-contracts").PatchOps | import("@c6o/kubeclient-contracts").PartialDeep<Resource>, options?: import("@c6o/kubeclient-contracts").PatchOptions): any;
        delete(object: Resource): any;
        upsert(object: Resource): any;
        exec(resource: Resource, command: string | string[], stdout?: import("stream").Writable, stderr?: import("stream").Writable, stdin?: import("stream").Readable): any;
        eachFile(fn: any, file: string, params?: any): any;
        upsertFile(file: string, params?: any): any;
        createFile(file: string, params?: any): any;
        deleteFile(file: string, params?: any): any;
        if(condition: boolean, trueCallback: import("@c6o/kubeclient-contracts").ifCallback, falseCallback?: import("@c6o/kubeclient-contracts").ifCallback): any;
        beginWatch(resource: Resource): any;
        whenWatch(conditionFn: any, actionFn: any): any;
        endWatch(): any;
    };
};
