import { LitElement, CSSResult } from 'lit-element';
import { ComboBoxElement } from '@vaadin/vaadin-combo-box/src/vaadin-combo-box';
export declare class IstioSettings extends LitElement {
    api: any;
    choicesService: any;
    disposer: any;
    grafanaNamespace: any;
    grafanaOptions: any;
    prometheusNamespace: any;
    prometheusOptions: any;
    httpsRedirect: boolean;
    busy: any;
    loaded: boolean;
    static get styles(): CSSResult[] | CSSResult;
    get grafanaComboBox(): ComboBoxElement;
    get prometheusComboBox(): ComboBoxElement;
    render(): import("lit-element").TemplateResult;
    renderGrafanaLink(): import("lit-element").TemplateResult;
    renderPrometheusLink(): import("lit-element").TemplateResult;
    httpsRedirectChanged: (e: any) => Promise<void>;
    linkGrafana: () => Promise<void>;
    linkPrometheus: () => Promise<void>;
    unlinkGrafana: () => Promise<void>;
    unlinkPrometheus: () => Promise<void>;
    resetSettings: () => Promise<void>;
    isBusy: (manifest: any) => boolean;
    renderSettings: (manifest: any) => Promise<void>;
    applyChanges: (e: any) => Promise<void>;
    connectedCallback(): Promise<void>;
}
