apiVersion: v1
data:
  intercept-nginx-config: |
    upstream 87abdaac7d43.ngrok.io {
        server 87abdaac7d43.ngrok.io:80;
    }
    upstream e237b327b383.ngrok.io {
        server e237b327b383.ngrok.io:80;
    }

    upstream decoy {
        server interceptor-halyard-backend-decoy:3000;
    }

    # https://sites.psu.edu/jasonheffner/2015/06/19/nginx-use-different-backend-based-on-http-header/
    map $http_x_select $whereTo {
        default "decoy";
        3020 "87abdaac7d43.ngrok.io";
        3010 "e237b327b383.ngrok.io";
    }

    server {
        listen       80;
        server_name  e237b327b383.ngrok.io;

      location / {
            proxy_pass http://$whereTo;

            proxy_set_header X-Real-IP $remote_addr;
            #proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-19T23:30:19Z"
  labels:
    system.codezero.io/session: 231d98ac5d095215f7225e94452254f6f914786a
  name: interceptor-halyard-backend
  namespace: halyard
  resourceVersion: "47582"
  uid: 38783e8e-ee56-404b-bcc4-59a619068589
