import { LitElement, CSSResult } from 'lit-element';
import { ComboBoxElement } from '@vaadin/vaadin-combo-box/src/vaadin-combo-box';
import { TextFieldElement } from '@vaadin/vaadin-text-field/src/vaadin-text-field';
export declare class TraxittSystemSettings extends LitElement {
    api: any;
    choicesService: any;
    disposer: any;
    loggingLink: any;
    loggerOptions: any;
    npmLink: any;
    npmOptions: any;
    prometheusLink: any;
    prometheusOptions: any;
    grafanaLink: any;
    grafanaOptions: any;
    busy: any;
    loaded: boolean;
    static get styles(): CSSResult[] | CSSResult;
    get loggerComboBox(): ComboBoxElement;
    get npmComboBox(): ComboBoxElement;
    get npmURL(): TextFieldElement;
    get npmUsername(): TextFieldElement;
    get npmPassword(): TextFieldElement;
    get grafanaComboBox(): ComboBoxElement;
    get prometheusComboBox(): ComboBoxElement;
    render(): import("lit-element").TemplateResult;
    get npmOptionsList(): any;
    linkNpm: () => Promise<void>;
    unlinkNpm: () => Promise<void>;
    renderNpmLink(): import("lit-element").TemplateResult;
    renderLoggingLink(): import("lit-element").TemplateResult;
    renderPrometheusLink(): import("lit-element").TemplateResult;
    renderGrafanaLink(): import("lit-element").TemplateResult;
    linkLogger: () => Promise<void>;
    unlinkLogger: () => Promise<void>;
    linkPrometheus: () => Promise<void>;
    unlinkPrometheus: () => Promise<void>;
    linkGrafana: () => Promise<void>;
    unlinkGrafana: () => Promise<void>;
    resetSettings: () => Promise<void>;
    isBusy: (manifest: any) => boolean;
    renderSettings: (manifest: any) => Promise<void>;
    applyChanges: (e: any) => Promise<void>;
    connectedCallback(): Promise<void>;
}
